# Configuration for dago-domenai
env: development
debug: true

database:
  # Default Postgres connection (override with DATABASE_URL in .env)
  postgres_url: "postgresql://domenai:password@localhost:5432/domenai"
  save_results: true  # Enable/disable database persistence

logging:
  level: INFO
  log_dir: ./logs

network:
  user_agent: DomainAnalyzerBot/1.0
  request_timeout: 10
  follow_redirects: true
  verify_ssl: true

checks:
  status:
    enabled: true
  redirect:
    enabled: true
    max_hops: 10
  robots:
    enabled: true
  sitemap:
    enabled: true
  ssl:
    enabled: true

# Export configuration
export:
  enabled: true
  format: both  # Options: 'json', 'csv', or 'both'
  directory: ./exports
  include_summary: true  # Generate summary statistics file