# Configuration for dago-domenai
env: development
debug: true

database:
  # Default Postgres connection (override with DATABASE_URL in .env)
  postgres_url: "postgresql://domenai:password@localhost:5432/domenai"
  save_results: true  # Enable/disable database persistence

logging:
  level: INFO
  log_dir: ./logs

network:
  user_agent: DomainAnalyzerBot/1.0
  request_timeout: 10
  follow_redirects: true
  verify_ssl: true

checks:
  whois:
    enabled: true
    # DAS (Domain Availability Service) configuration for domreg.lt
    # DAS is the official bulk checking protocol from Lithuanian domain registry
    server: das.domreg.lt
    port: 4343
    timeout: 5.0  # Socket timeout in seconds
    rate_limit: 4  # Max queries per second (DAS supports "several dozens/sec")
  status:
    enabled: true
  redirect:
    enabled: true
    max_hops: 10
  robots:
    enabled: true
  sitemap:
    enabled: true
  ssl:
    enabled: true

# Export configuration
export:
  enabled: true
  format: both  # Options: 'json', 'csv', or 'both'
  directory: ./exports
  include_summary: true  # Generate summary statistics file
# v0.9 - Smart Redirect Capture Configuration
redirect_capture:
  enabled: true
  
  # Only capture domains with these TLDs
  target_tlds:
    - '.lt'
  
  # Keep full subdomains for these patterns (don't strip to root)
  # Example: stat.gov.lt and lrv.gov.lt are different government agencies
  keep_subdomains_for:
    - '.gov.lt'   # Government agencies
    - '.lrv.lt'   # Lithuanian government
    - '.edu.lt'   # Educational institutions
    - '.mil.lt'   # Military
  
  # Don't capture these common services (not useful for analysis)
  ignore_common_services:
    - 'google.lt'
    - 'maps.google.lt'
    - 'facebook.com'
    - 'youtube.com'
    - 'linkedin.com'
    - 'twitter.com'
    - 'instagram.com'
    - 'google.com'
    - 'googleapis.com'
    - 'gstatic.com'
    - 'cloudflare.com'
    - 'cloudfront.net'
    - 'amazonaws.com'
  
  # Track discovery relationships for analytics
  track_discoveries: true
